export const Str = {
  earnChannel: "https://t.me/+QvfqIlQfQPEzZDM0",
  whatsappHelp: "https://wa.link/ejqshz",
  signupUrl: "https://app.letbase.co/request-invite",
  baseUrlDev: 'http://localhost:3001',
  baseUrlProd: 'https://api.homelett.co',
  CV_TEMPLATES: {
    CV_1: {
      key: "CV_1",
    },
    CV_2: {
      key: "CV_2",
    },
    CV_3: {
      key: "CV_3",
    },
    CV_4: {
      key: "CV_4",
    },
  },
  storeBrands: [
    "/logos/aliexpress.jpeg",
    "/logos/canada_icon.webp",
  ],
  brands: [
    "/logos/wifi.png",
    "/logos/yt.png",
    "/logos/sp.png",
    "/logos/pr.jpeg",
    "/logos/nt.png",
    "/logos/sm.png",
    "/logos/windscribe_logo.jpg",
  ],
  utilityBrands: [
    "/logos/gramma.png",
    "/logos/canva.webp",
    "/logos/chatgpt.png",
    "/logos/nordvpn.png",
  ],
  courseBrands: ["/logos/udemy.png", "/logos/coursera.png"],
  platforms: [
    {
      value: "1",
      label: "Youtube premium",
      pricingAmount: 1700,
      pricingName: "Family plan",
      earning: 35,
      icon: "/logos/yt.png",
    },
    {
      value: "18",
      label: "Showmax Sport + Movie",
      pricingAmount: 4600,
      pricingName: "Sport + Movie Plan",

      earning: 25,
      icon: "/logos/sm.png",
    },
    {
      value: "3",
      label: "Spotify Family",
      pricingAmount: 1400,
      pricingName: "Family plan",
      earning: 35,
      icon: "/logos/sp.png",
    },
    {
      value: "2",
      label: "Netflix",
      pricingName: "Premium plan",
      pricingAmount: 5000,
      earning: 25,
      icon: "/logos/nt.png",
    },
    {
      value: "4",
      label: "ShowMax",
      pricingAmount: 3500,
      pricingName: "All devices plan",

      earning: 30,
      icon: "/logos/sm.png",
    },

    {
      value: "5",
      label: "Prime video",
      pricingAmount: 2300,
      pricingName: "All devices plan",
      earning: 35,
      icon: "/logos/pr.jpeg",
    },
  ],
  dataPlans: [
    {
      value: "500",
      network: "mtn",
      label: "MTN SME Data 500MB – 30 Days",
      price: 199,
    },
    {
      value: "M1024",
      network: "mtn",
      label: "MTN SME Data 1GB – 30 Days",
      price: 339,
    },
    {
      value: "M2024",
      network: "mtn",
      label: "MTN SME Data 2GB – 30 Days",
      price: 679,
    },
    {
      value: "3000",
      network: "mtn",
      label: "MTN SME Data 3GB – 30 Days",
      price: 1019,
    },
    {
      value: "5000",
      network: "mtn",
      label: "MTN SME Data 5GB – 30 Days",
      price: 1699,
    },
    {
      value: "10000",
      network: "mtn",
      label: "MTN SME Data 10GB – 30 Days",
      price: 3399,
    },
    {
      value: "mtn-20hrs-1500",
      network: "mtn",
      label: "MTN Data 6GB – 7 Days",
      price: 1499,
    },
    {
      value: "mtn-30gb-8000",
      network: "mtn",
      label: "MTN Data 30GB – 30 Days",
      price: 7959,
    },
    {
      value: "mtn-40gb-10000",
      network: "mtn",
      label: "MTN Data 40GB – 30 Days",
      price: 9899,
    },
    {
      value: "mtn-75gb-15000",
      network: "mtn",
      label: "MTN Data 75GB – 30 Days",
      price: 14979,
    },
    {
      value: "glo100x",
      network: "glo",
      label: "Glo Data 1GB – 5 Nights",
      price: 100, // Assuming price not provided
    },
    {
      value: "glo200x",
      network: "glo",
      label: "Glo Data 1.25GB – 1 Day (Sunday)",
      price: 200, // Assuming price not provided
    },
    {
      value: "G500",
      network: "glo",
      label: "Glo Data 1.35GB – 14 Days",
      price: 500, // Assuming price not provided
    },
    {
      value: "G2000",
      network: "glo",
      label: "Glo Data 5.8GB – 30 Days",
      price: 2000, // Assuming price not provided
    },
    {
      value: "G1000",
      network: "glo",
      label: "Glo Data 2.9GB – 30 Days",
      price: 1000, // Assuming price not provided
    },
    {
      value: "G2500",
      network: "glo",
      label: "Glo Data 7.7GB – 30 Days",
      price: 2500, // Assuming price not provided
    },
    {
      value: "G3000",
      network: "glo",
      label: "Glo Data 10GB – 30 Days",
      price: 3000, // Assuming price not provided
    },
    {
      value: "G4000",
      network: "glo",
      label: "Glo Data 13.25GB – 30 Days",
      price: 4000, // Assuming price not provided
    },
    {
      value: "G5000",
      network: "glo",
      label: "Glo Data 18.25GB – 30 Days",
      price: 5000, // Assuming price not provided
    },
    {
      value: "G8000",
      network: "glo",
      label: "Glo Data 29.5GB – 30 Days",
      price: 8000, // Assuming price not provided
    },
    {
      value: "glo10000",
      network: "glo",
      label: "Glo Data 50GB – 30 Days",
      price: 10000, // Assuming price not provided
    },
    {
      value: "AIRTEL500MB",
      network: "airtel",
      label: "Airtel Data 500MB (Gift) – 30 Days",
      price: 199,
    },
    {
      value: "AIRTEL1GB",
      network: "airtel",
      label: "Airtel Data 1GB (Gift) – 30 Days",
      price: 339,
    },
    {
      value: "AIRTEL2GB",
      network: "airtel",
      label: "Airtel Data 2GB (Gift)– 30 Days",
      price: 679,
    },
    {
      value: "AIRTEL5GB",
      network: "airtel",
      label: "Airtel Data 5GB (Gift)– 30 Days",
      price: 1699,
    },
    {
      value: "AIRTEL10GB",
      network: "airtel",
      label: "Airtel Data 10GB (Gift)– 30 Days",
      price: 3399,
    },
    {
      value: "AIRTEL15GB",
      network: "airtel",
      label: "Airtel Data 15GB (Gift)– 30 Days",
      price: 4999,
    },
    {
      value: "AIRTEL20GB",
      network: "airtel",
      label: "Airtel Data 20GB (Gift)– 30 Days",
      price: 5999,
    },
    {
      value: "airt-1100",
      network: "airtel",
      label: "Airtel Data 1.5GB – 30 Days",
      price: 1079,
    },
    {
      value: "airt-1300",
      network: "airtel",
      label: "Airtel Data 2GB – 30 Days",
      price: 1289,
    },
    {
      value: "airt-1650",
      network: "airtel",
      label: "Airtel Data 3GB – 30 Days",
      price: 1639,
    },
    {
      value: "airt-2200",
      network: "airtel",
      label: "Airtel Data 4.5GB – 30 Days",
      price: 2189,
    },
    {
      value: "airt-3300",
      network: "airtel",
      label: "Airtel Data 10GB – 30 Days",
      price: 3289,
    },
    {
      value: "airt-5500",
      network: "airtel",
      label: "Airtel Data 20GB – 30 Days",
      price: 5489,
    },
    {
      value: "airt-11000",
      network: "airtel",
      label: "Airtel Data 40GB – 30 Days",
      price: 10799,
    },
    {
      value: "airt-330x",
      network: "airtel",
      label: "Airtel Data 1GB – 1 Day",
      price: 329,
    },
    {
      value: "airt-550",
      network: "airtel",
      label: "Airtel Data 750MB – 14 Days",
      price: 545,
    },
    {
      value: "airt-1650-2",
      network: "airtel",
      label: "Airtel Data 6GB – 7 Days",
      price: 1639,
    },
    {
      value: "9MOB1000",
      network: "9mobile",
      label: "9mobile Data 1GB – 30 Days",
      price: 1000, // Assuming price not provided
    },
    {
      value: "9MOB34500",
      network: "9mobile",
      label: "9mobile Data 2.5GB – 30 Days",
      price: 3450, // Assuming price not provided
    },
    {
      value: "9MOB8000",
      network: "9mobile",
      label: "9mobile Data 11.5GB – 30 Days",
      price: 8000, //
    },
    {
      value: "9MOB5000",
      network: "9mobile",
      label: "9mobile Data 15.5GB – 30 Days",
      price: 12000, //
    },
  ],

  products: [
    "/logos/yt.png",
    "/logos/sp.png",
    "/logos/pr.jpeg",
    "/logos/nt.png",
    "/logos/sm.png",
  ],

  industryCategories: [
    "Information Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Manufacturing",
    "Retail",
    "Hospitality",
    "Media & Entertainment",
    "Construction",
    "Transportation",
    "Telecommunications",
    "Energy",
    "Agriculture",
    "Government",
    "Non-profit",
    "Consulting",
    "Real Estate",
    "Legal",
    "Automotive",
    "Food & Beverage",
    "Fashion",
    "Travel",
    "Fitness & Wellness",
    "Insurance",
    "Biotechnology",
    "Pharmaceutical",
    "Environmental",
    "Marketing",
    "Advertising",
    "Design",
    "Engineering",
    "Art & Design",
    "Architecture",
    "Music",
    "Sports",
    "Gaming",
    "Science",
    "Research",
    "Writing & Editing",
    "Human Resources",
    "Customer Service",
    "Sales",
    "Management",
    "Operations",
    "Administration",
    "Quality Assurance",
    "Other",
  ],
  dummyJobs: [
    {
      id: 1,
      name: "Principal Mobile Engineer",
      company: "GitLab Inc",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/gitlab.png",
    },
    {
      id: 2,
      name: "HTML/Email Developer",
      company: "Kraken wallet",
      location: "California",
      salary: 12300,
      logo: "/logos/krakenfx_logo.jpeg",
    },
    {
      id: 3,
      name: "Senior Frontend Engineer  (Portfolio, Assets, and NFTs)",
      company: "MoniePoint",
      location: "Nigeria, Remote",
      salary: 1900,
      logo: "/logos/monie.jpeg",
    },
    {
      name: "Product Designer / Front End engineer",
      company: "Binance",
      location: "Remote",
      salary: 1900,
      logo: "/logos/binance.png",
    },
    {
      name: "Lead Frontend Developer ",
      company: "Trust wallet",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/trust.jpeg",
    },
    {
      name: "Senior Frontend Product Engineer",
      company: "Canva",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/canva.jpeg",
    },
    {
      name: "Senior Frontend Developer – Next.js",
      company: "FlutterWave",
      location: "India, Remote",
      salary: 1900,
      logo: "/logos/flutterwave.jpeg",
    },
    {
      name: "Junior Full Stack Developer [Full Remote]",
      company: "LemFi",
      location: "India, Remote",
      salary: 1900,
      logo: "/logos/lemfi.png",
    },
    {
      name: "React frontend Developer",
      company: "TalentHouse",
      location: "USA, Remote",
      salary: 1900,
    },
    {
      name: "Senior Frontend Engineer",
      company: "Consys wallet",
      location: "United kingdom",
      salary: 1900,
    },
    {
      name: "React Developer",
      company: "PiggyVest",
      location: "Nigeria, Remote",
      salary: 1900,
      logo: "/logos/piggy.png",
    },
    {
      name: "Software Development Engineer (Front End)",
      company: "Mono INC",
      location: "Nigeria, Lekki",
      salary: 1900,
      logo: "/logos/mono.png",
    },
  ],
};
