export const Str = {
  whatsappHelp:
    "https://api.whatsapp.com/send?phone=2347018135800&text=I%20need%20to%20help",
  whatsapp:
    "https://api.whatsapp.com/send?phone=2347018135800&text=I%20want%20to%20start%20a%20subscription",
  CV_TEMPLATES: {
    CV_1: {
      key: "CV_1",
    },
    CV_2: {
      key: "CV_2",
    },
    CV_3: {
      key: "CV_3",
    },
    CV_4: {
      key: "CV_4",
    },
  },
  brands: [
    "/logos/yt.webp",
    "/logos/sp.png",
    "/logos/pr.jpeg",
    "/logos/nt.png",
    "/logos/sm.png",
    "/logos/windscribe_logo.jpg",
  ],

  dataPlans: {
    mtn: [
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "4Gig data @ 200", value: "200 @1gig" },
      { label: "1Gig data @ 100", value: "200 @1gig" },
      { label: "1Gig data @ 100", value: "300 @1gig" },
    ],
    airtel: [
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "4Gig data @ 200", value: "100 @1gig" },
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "1Gig data @ 100", value: "100 @1gig" },
    ],
    glo: [
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "4Gig data @ 200", value: "100 @1gig" },
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "1Gig data @ 100", value: "100 @1gig" },
    ],
    "9mobile": [
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "4Gig data @ 200", value: "100 @1gig" },
      { label: "1Gig data @ 100", value: "100 @1gig" },
      { label: "1Gig data @ 100", value: "100 @1gig" },
    ],
  },

  products: [
    "/logos/yt.webp",
    "/logos/sp.png",
    "/logos/pr.jpeg",
    "/logos/nt.png",
    "/logos/sm.png",
  ],

  industryCategories: [
    "Information Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Manufacturing",
    "Retail",
    "Hospitality",
    "Media & Entertainment",
    "Construction",
    "Transportation",
    "Telecommunications",
    "Energy",
    "Agriculture",
    "Government",
    "Non-profit",
    "Consulting",
    "Real Estate",
    "Legal",
    "Automotive",
    "Food & Beverage",
    "Fashion",
    "Travel",
    "Fitness & Wellness",
    "Insurance",
    "Biotechnology",
    "Pharmaceutical",
    "Environmental",
    "Marketing",
    "Advertising",
    "Design",
    "Engineering",
    "Art & Design",
    "Architecture",
    "Music",
    "Sports",
    "Gaming",
    "Science",
    "Research",
    "Writing & Editing",
    "Human Resources",
    "Customer Service",
    "Sales",
    "Management",
    "Operations",
    "Administration",
    "Quality Assurance",
    "Other",
  ],
  dummyJobs: [
    {
      id: 1,
      name: "Principal Mobile Engineer",
      company: "GitLab Inc",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/gitlab.png",
    },
    {
      id: 2,
      name: "HTML/Email Developer",
      company: "Kraken wallet",
      location: "California",
      salary: 12300,
      logo: "/logos/krakenfx_logo.jpeg",
    },
    {
      id: 3,
      name: "Senior Frontend Engineer  (Portfolio, Assets, and NFTs)",
      company: "MoniePoint",
      location: "Nigeria, Remote",
      salary: 1900,
      logo: "/logos/monie.jpeg",
    },
    {
      name: "Product Designer / Front End engineer",
      company: "Binance",
      location: "Remote",
      salary: 1900,
      logo: "/logos/binance.png",
    },
    {
      name: "Lead Frontend Developer ",
      company: "Trust wallet",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/trust.jpeg",
    },
    {
      name: "Senior Frontend Product Engineer",
      company: "Canva",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/canva.jpeg",
    },
    {
      name: "Senior Frontend Developer – Next.js",
      company: "FlutterWave",
      location: "India, Remote",
      salary: 1900,
      logo: "/logos/flutterwave.jpeg",
    },
    {
      name: "Junior Full Stack Developer [Full Remote]",
      company: "LemFi",
      location: "India, Remote",
      salary: 1900,
      logo: "/logos/lemfi.png",
    },
    {
      name: "React frontend Developer",
      company: "TalentHouse",
      location: "USA, Remote",
      salary: 1900,
    },
    {
      name: "Senior Frontend Engineer",
      company: "Consys wallet",
      location: "United kingdom",
      salary: 1900,
    },
    {
      name: "React Developer",
      company: "PiggyVest",
      location: "Nigeria, Remote",
      salary: 1900,
      logo: "/logos/piggy.png",
    },
    {
      name: "Software Development Engineer (Front End)",
      company: "Mono INC",
      location: "Nigeria, Lekki",
      salary: 1900,
      logo: "/logos/mono.png",
    },
  ],
};
