export const Str = {
  dummyJobs: [
    {
      name: "Principal Mobile Engineer",
      company: "GitLab Inc",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/gitlab.png",
    },
    {
      name: "HTML/Email Developer",
      company: "Kraken wallet",
      location: "California",
      salary: 12300,
      logo: "/logos/krakenfx_logo.jpeg",
    },
    {
      name: "Product Designer / Front End engineer",
      company: "Binance",
      location: "Remote",
      salary: 1900,
      logo: "/logos/binance.png",
    },
    {
      name: "Senior Frontend Engineer - MetaMask (Portfolio, Assets, and NFTs)",
      company: "MoniePoint",
      location: "Nigeria, Remote",
      salary: 1900,
      logo: "/logos/monie.jpeg",
    },
    {
      name: "Lead Frontend Developer ",
      company: "Trust wallet",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/trust.jpeg",
    },
    {
      name: "Senior Frontend Product Engineer",
      company: "Canva",
      location: "United kingdom",
      salary: 1900,
      logo: "/logos/canva.jpeg",
    },
    {
      name: "Senior Frontend Developer – Next.js",
      company: "FlutterWave",
      location: "India, Remote",
      salary: 1900,
      logo: "/logos/flutterwave.jpeg",
    },
    {
      name: "Junior Full Stack Developer [Full Remote]",
      company: "LemFi",
      location: "India, Remote",
      salary: 1900,
      logo: "/logos/lemfi.png",
    },
    {
      name: "React frontend Developer",
      company: "TalentHouse",
      location: "USA, Remote",
      salary: 1900,
    },
    {
      name: "Senior Frontend Engineer",
      company: "Consys wallet",
      location: "United kingdom",
      salary: 1900,
    },
    {
      name: "React Developer",
      company: "PiggyVest",
      location: "Nigeria, Remote",
      salary: 1900,
      logo: "/logos/piggy.png",
    },
    {
      name: "Software Development Engineer (Front End)",
      company: "Mono INC",
      location: "Nigeria, Lekki",
      salary: 1900,
      logo: "/logos/mono.png",
    },
  ],
};
